version: '3.7'

services:
  weight_tracker_api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/src
    ports:
      - "9000:9000"
      - "5678:5678"
  weight_tracker_db:
    image: postgres:15-bookworm
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_data_backups:/backups
      - ./scripts/postgres:/scripts

volumes:
  pg_data:
  pg_data_backups: